# Generated by Django 4.2.4 on 2023-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentTransactionToken', models.CharField(max_length=250)),
                ('debutCardno', models.CharField(max_length=25)),
                ('cardHolderNames', models.CharField(max_length=25)),
                ('expiredDate', models.CharField(max_length=25)),
                ('cvvcode', models.CharField(max_length=25)),
                ('amount', models.BigIntegerField()),

            ],
        ),
    ]
