# Generated by Django 4.2.4 on 2023-08-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('mealId', models.AutoField(primary_key=True, serialize=False)),
                ('mealName', models.CharField(max_length=25)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('isAvailable', models.IntegerField()),
            ],
        ),
    ]
