# Generated by Django 4.2.4 on 2023-08-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=25)),
                ('lastName', models.CharField(max_length=25)),
                ('phoneNo', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('idNo', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=25)),
            ],
        ),
    ]
